name: AI4UA
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py310haa95532_0
  - libffi=3.4.2=hd77b12b_6
  - openssl=1.1.1s=h2bbff1b_0
  - pip=22.3.1=py310haa95532_0
  - python=3.10.9=h966fe2a_0
  - setuptools=65.6.3=py310haa95532_0
  - sqlite=3.40.1=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2022g=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.10=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - contourpy==1.0.7
      - cycler==0.11.0
      - fonttools==4.38.0
      - kiwisolver==1.4.4
      - matplotlib==3.6.3
      - networkx==3.0
      - numpy==1.24.1
      - packaging==23.0
      - pillow==9.4.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - six==1.16.0
      - torch==1.13.1
      - typing-extensions==4.4.0
